apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-multi-env
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: product-dev
          - environment: staging
            namespace: product-staging
          - environment: prod
            namespace: product-prod
  template:
    metadata:
      name: 'product-{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/letslearn207/flipkart-gitops.git
        targetRevision: HEAD
        path: apps/product
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
